### ISSUE TITLE
Title font not resizing for smaller viewport

### ISSUE THREAD

**Issue by bringbackthedog** [mattcoding4days/VI-Solutions#1]
![capture](https://user-images.githubusercontent.com/34327253/76242867-9d77a580-61f4-11ea-8bba-97d04d1f8613.jpg)
![capture1](https://user-images.githubusercontent.com/34327253/76242876-a1a3c300-61f4-11ea-9a9f-0fc2da1c77b6.jpg)

**Comment by mattcoding4days** [comment]
Ahh yes, I will start working on that today, going to replace that nav bar with a thicker style, so we can properly display the Carbon Solutions logo

**Comment by mattcoding4days** [comment]
Issue fixed
